### ISSUE TITLE
Service Integration Authentication

### ISSUE THREAD

**Issue by vegnnt** [docusign/postman-esign-api-collection#1]
This repo is for new users. But it is using the legacy header authentication. 

Please rework this repo to use service integration authentication with user consent and any other steps new users need to get started with the service integration authentication. And please draft a new blog post. 

https://www.docusign.com/blog/dsdev-please-mr-postman/
https://docusign.github.io/postman-esign-api-collection/
https://docs.docusign.com/esign/guide/authentication/oa2_jwt.html

**Comment by LarryKlugerDS** [comment]
I apologize for the extremely slow response to this issue. We have changed our processes so this won't happen again.

Meanwhile, good news is that we have removed all legacy header auth from the collection.
