### ISSUE TITLE
Auth Code Grant Access Token script should store refresh token

### ISSUE THREAD

**Issue by svodnik** [docusign/postman-esign-api-collection#24]
For the Authentication > 01 Authorize Code Grant Access Token request, the test script stores the `access_token` value as an environment variable, but doesn't store the `refresh_token` value. This means that Authentication > 03 Refresh Access Token doesn't work without manual configuration. This can be fixed by adding a single line of code to the test script for 01.
I'd prefer not to go through forking this to add one line of code, so I'm hoping someone else has the code ready and can easily implement this. The new line of code should be
```js
postman.setEnvironmentVariable("refreshToken", jsonData.refresh_token);
```

**Comment by RajRele** [comment]
This is fixed with https://github.com/docusign/postman-esign-api-collection/pull/25 and https://github.com/docusign/postman-esign-api-collection/pull/26 
Thanks!
